# docker-compose.yml

# version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  bot:
    build: .
    environment:
      - TZ=Europe/Moscow
    env_file: .env
    depends_on:
      - db
    restart: always

volumes:
  db_data:
